trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true  # Permitir scripts acessar o token OAuth
  #fetchDepth: 0  # Buscar todo o histórico

#- task: UsePythonVersion@0
#  inputs:
#    versionSpec: '3.x'
#    addToPath: true

- powershell: |

    # Getting the pbix files list from the Repos.
    Write-Host "##[debug] Getting pbix report files to deploy in workspace"
    $pbixReports = Get-ChildItem -Path "$(Build.SourcesDirectory)" -Recurse -Filter *.pbix

    # To each file in the list of pbix files, set attribute
    foreach ($reportFile in $pbixReports) { # including the path
      Write-Host "##[debug] PBIX file full name: $($reportFile.FullName)" # Including path

      # Obter atributo do arquivo
      $attribute = git check-attr devDeployDate  $reportFile.FullName
      Write-Host "Atributo do arquivo: $($attribute)"
    }

  displayName: 'Recuperar Atributo do Arquivo'